export const axisXWindow = 450
export const axisYWindow = 600
export const topHeight = 40
export const marginBetweenPages = 50
export const buttonToAddingPages = 32
export const centerAxisX = axisXWindow/2
export const centerAxisY = axisYWindow/2
export const fullHeightPage = axisYWindow + marginBetweenPages + buttonToAddingPages
export const baseUrl = 'http://127.0.0.1:5000/api/'